### ISSUE TITLE
Roadmap discussion.

### ISSUE THREAD

**Issue by KDr2** [TuringLang/Torch.jl#5]
In my plan, the roadmap is:
- [x] construct Tensor from Julia Array
- [x] convert Tensor to Julia Array
- [x] Scalar type support
- [x] auto-generate APIs of Tensor
- [x] implement the Julia Array interface for Tensor
- [ ] ~~write some convenient APIs on the top of the auto-generate APIs~~

In the meantime,  I renamed the shared library from "libjtorch.so" to "libtorch_capi.so". I want to ensure that in the c++ side (the code of the shared library) there are no Julia things so that any language that has an adequate FFI (a facility like Julia's ccall) can use this shared lib to wrap a lib in that language easily.

**Comment by yebai** [comment]
This looks like a sensible plan to me. Let's focus on providing a minimal, well-documented wrapping of Tensor and its gradient functions. 

In addition, maybe rename our work to `TorchArrays` to avoid a name clash with `Torch.jl`.

**Comment by KDr2** [comment]
👍 Both `TorchArrays` and `ThArrays` look good to me, something like `XxxTensor` is also a choice.

**Comment by KDr2** [comment]
I just tagged the first version, v0.0.1, should we consider to rename the project now?

**Comment by yebai** [comment]
Sure, please go ahead to rename the package, and maybe get it registered too.

**Comment by KDr2** [comment]
@JuliaRegistrator register

**Comment by KDr2** [comment]
@JuliaRegistrator register

**Comment by KDr2** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register
